FROM node:24.0-alpine AS deps

WORKDIR /app

COPY ./package*.json ./
COPY ./.npmrc ./

RUN npm install

FROM node:24.0-alpine AS app

WORKDIR /app

COPY --from=deps /app/node_modules/ ./node_modules/

COPY . .

CMD [ "npm", "run", "dev" ]
