import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { fetchUsers } from "@/repository";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const users: User[] = await fetchUsers();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-row min-h-screen`}
      >
        <aside className="border-r py-4 px-2 overflow-y-auto max-w-60 w-full">
          <ul className="space-y-2">
            <li className="mb-3">
              <h2 className="text-xl font-semibold">Users</h2>
              <hr />
            </li>
            {users.map((user) => (
              <li key={user.id}>
                <Link
                  className="block overflow-hidden px-2 py-2 text-nowrap whitespace-nowrap text-ellipsis bg-slate-300 hover:bg-slate-400 rounded-sm"
                  href={`/users/${user.id}`}
                >
                  <span>{user.name}</span>
                </Link>
              </li>
            ))}
          </ul>
        </aside>
        {children}
      </body>
    </html>
  );
}
